Add should_fail command. Run all tests with set -x (fail on errors).

diff --git a/run_test b/run_test
--- a/run_test
+++ b/run_test
@@ -1,14 +1,31 @@
-#!/usr/bin/env bash
 # Run test scripts listed on the command line
 #
 # This is a modified version of https://gist.github.com/1300101
 # which is specialized for running node tests.
 
-echo
+if [ $# == 0 ]; then
+    echo "Usage: $0 [test shell scripts]"
+    exit 1
+fi
+
+# This function can be used in test scripts to indicate that
+# the rest of the line is a command that is expected to fail.
+function should_fail() {
+    "$@"
+    return ! $?
+}
+
 for file in $@; do
-  printf "\033[90m   ${file#test/}\033[0m "
-  $(readlink -f $file) && printf "\033[36m✓\033[0m\n"
-  test $? -eq 0 || exit $?
+    printf "\033[90m   ${file#test/}\033[0m "
+
+    # Make a modified version of the test script that starts with set -x. That
+    # way the test will abort with an error message if any of its calls fails.
+    test_tmp=`mktemp /tmp/test_XXXXX.sh`
+    (echo "set -x"; cat $file) > $test_tmp
+
+    bash $test_tmp && printf "\033[36m✓\033[0m\n"
+
+    test $? -eq 0 || exit $?
 done
-echo
+echo "All tests passed." 
 
